services:
  db:
    container_name: ${DB_HOST}
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql